name: test

on:
  # Every push onto the main branch and releases triggers a retest.
  push:
    branches:
      - master
      - v12-branch
  # All pull_requests trigger a retest.
  pull_request:

jobs:

  mac:
    strategy:
      fail-fast: false
    runs-on: macos-latest
    name: '🍏 macOS'
    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install bison

    - name: Build, check and install
      run: |
        export PATH="/usr/local/opt/bison/bin:$PATH"
        autoconf
        ./configure
        make check
        sudo make install

    - name: Test
      run: ./.github/test.sh


  lin:
    strategy:
      fail-fast: false
      matrix:
        os: [
          '20.04',
          '22.04'
        ]
    runs-on: ubuntu-${{ matrix.os }}
    name: '🐧 Ubuntu ${{ matrix.os }}'
    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update -qq
        sudo apt install -y make g++ git bison flex gperf libreadline-dev autoconf python3-sphinx

    - name: Build, check and install
      run: |
        autoconf
        ./configure
        make check
        sudo make install

    - name: Test
      run: ./.github/test.sh

    - name: Documentation
      run: |
        cd Documentation
        make html

  win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64 },
          { msystem: MINGW32, arch: i686 }
        ]
    name: 🟪 ${{ matrix.msystem}} · ${{ matrix.arch }}
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_ARCH: ${{ matrix.msystem }}
    steps:

    - run: git config --global core.autocrlf input
      shell: bash

    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        install: >
          git
          base-devel
          gperf
          mingw-w64-${{ matrix.arch }}-toolchain

    - name: Build and check
      run: |
        cd msys2
        makepkg-mingw --noconfirm --noprogressbar -sCLf

    - name: Install
      run: pacman -U --noconfirm msys2/*.zst

    - name: Test
      run: ./.github/test.sh

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.msystem }}-${{ matrix.arch }}
        path: msys2/*.zst
